image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install

vscode:
  extensions:
    - rebornix.ruby@0.27.0:b86Iqz+ryuS7Nr77EyIClA==
    - wingrunr21.vscode-ruby@0.27.0:VymtAvJQnv5jef/FsPtqJw==
    - davidanson.vscode-markdownlint@0.38.0:MCcSWKBmgWaXjm6m9AHE2Q==
    - yzhang.markdown-all-in-one@3.4.0:GR9Y7wA3m2/LsuZxLaCFtg==
    - rogalmic.bash-debug@0.3.9:8w+xOBwrJt9TA7S1JlrZng==
    - mads-hartmann.bash-ide-vscode@1.11.0:VLESO/tPCjrfzzLcJy83aQ==
    - timonwong.shellcheck@0.12.2:rNYWy8+G5JQ4FGeagKUjeg==
    - misogi.ruby-rubocop@0.8.5:nzEXfgn9DPI21vRRdceYBQ==
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
