branches:
  only:
    - "master"
language: generic
os: linux
dist: bionic
services:
  - xvfb
before_install:
  - curl -fsSLo- https://raw.githubusercontent.com/felipecassiors/scripts/master/install_virtualbox.sh | bash
  - curl -fsSLo- https://raw.githubusercontent.com/felipecassiors/scripts/master/install_vagrant.sh | bash
script:
  - set -e
  - vagrant up
  - vagrant package --vagrantfile src/Vagrantfile
before_deploy:
  - vagrant destroy -f # Save some disk space in case we need in the deploy test
  - nvm install lts/*
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    all_branches: true
