branches:
  only:
    - "master"
    - "test"
language: generic
os: linux
dist: bionic
services:
  - xvfb
before_install:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/felipecassiors/scripts/master/linux/install_virtualbox_deb.sh)"
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/felipecassiors/scripts/master/install_vagrant.sh)"
script:
  - set -e
  - ci/lint.sh
  - vagrant up

before_deploy:
  - vagrant package --vagrantfile src/Vagrantfile
  - vagrant destroy -f # Save some disk space in case we need in the deploy test
  - nvm install --lts
  - npm install

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ci/deploy_test.sh
    on:
      branch: test
