language: generic
os: linux
dist: bionic

services:
  - xvfb

before_install:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/felipecrs/scripts/HEAD/linux/install_virtualbox_deb.sh)"
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/felipecrs/scripts/HEAD/install_vagrant.sh)"

script:
  - set -e
  - scripts/lint.sh
  - vagrant up

before_deploy:
  - nvm install --lts
  - npm install

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      all_branches: true
